### ISSUE TITLE
Change full-page background for landing page - thoughts?

### ISSUE THREAD

**Issue by goudbes** [haheskja/scp-website#5]
Unsure whether this is the best solution for adding a different full-page background on landing page. Could it be done in a better way?  @haheskja 

[Code](https://github.com/haheskja/scp-website/commit/58081c89062e53f13682dd5d6defac5813dcdc5d#r41627213)

**Comment by haheskja** [comment]
I think it looks good, seems like a simple and good way to do it, at least for now until we decide on some more design aspects
